name: Build IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install Dependencies
        run: |
          cd Stremio-iOS
          pod install

      - name: Build and Archive App
        run: |
          cd Stremio-iOS
          xcodebuild -workspace Stremio.xcworkspace \
                     -scheme Stremio \
                     -destination 'generic/platform=iOS' \
                     -configuration Release \
                     clean archive \
                     -archivePath $PWD/Stremio.xcarchive

      - name: Export IPA
        run: |
          cd Stremio-iOS
          xcodebuild -exportArchive \
                     -archivePath $PWD/Stremio.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $PWD

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Stremio.ipa
          path: Stremio-iOS/Stremio.ipa
