name: Build IPA

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Archive App
        run: |
          xcodebuild -project Stremio.xcodeproj \
                     -scheme Stremio \
                     -destination 'generic/platform=iOS' \
                     -configuration Release \
                     clean archive \
                     -archivePath $PWD/Stremio.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath $PWD/Stremio.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath $PWD

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Stremio.ipa
          path: Stremio.ipa
